// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDO7AAw13po73g5oU84dr6aPwm1cPWwI',
    appId: '1:630265979133:web:YOUR_WEB_APP_ID',
    messagingSenderId: '630265979133',
    projectId: 'studentportal-78dcf',
    authDomain: 'studentportal-78dcf.firebaseapp.com',
    storageBucket: 'studentportal-78dcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDO7AAw13po73g5oU84dr6aPwm1cPWwI',
    appId: '1:630265979133:android:29c5eb678ffefd6b225e94',
    messagingSenderId: '630265979133',
    projectId: 'studentportal-78dcf',
    storageBucket: 'studentportal-78dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDO7AAw13po73g5oU84dr6aPwm1cPWwI',
    appId: '1:630265979133:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '630265979133',
    projectId: 'studentportal-78dcf',
    storageBucket: 'studentportal-78dcf.firebasestorage.app',
    iosBundleId: 'com.studentportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDO7AAw13po73g5oU84dr6aPwm1cPWwI',
    appId: '1:630265979133:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '630265979133',
    projectId: 'studentportal-78dcf',
    storageBucket: 'studentportal-78dcf.firebasestorage.app',
    iosBundleId: 'com.studentportal',
  );
}
